USE SQLL;

-- TOP-N ANALYSIS  FOR ORCALE DATABASE
-- SELECT ROWNUM AS RANK, ENAME,SAL FROM (SELECT FNAME,LNAME,SAL FROM GF ORDER BY SAL DESC ) WHERE ROWNUM <=5; 

-- MYSQL
WITH RankedSalaries AS (
    SELECT ENAME, SAL,
           ROW_NUMBER() OVER (ORDER BY SAL DESC) AS RANK
    FROM GF
)
SELECT rank, ENAME, SAL
FROM RankedSalaries
WHERE rank <= 2;

SELECT * FROM GF;